{{- if and .Values.collector.enabled (not .Values.collector.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "console.collector.secretName" . }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
    {{- include "console.collector.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.collector.secrets }}
  {{- if ne (toString $v) "" }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
{{- end }}
