{{- if not .Values.portal.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "console.portal.secretName" . }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
    {{- include "console.portal.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.portal.secrets }}
  {{- if ne (toString $v) "" }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
{{- end }}
