apiVersion: v2
name: namespace
description: "Создаёт рабочее пространство команды в кластере: квоты на ресурсы и собственную подсеть."
type: application
version: "6.1.0"
dependencies:
  - name: waypoint
    version: "2.3.0"
    repository: "file://../waypoint"
    condition: serviceMesh.waypoint
icon: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIj4KICA8dGl0bGU+TmFtZXNwYWNlPC90aXRsZT4KICA8ZyBzdHJva2U9IiMzMjhCQUYiIHN0cm9rZS13aWR0aD0iMS44IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiPgogICAgPHBhdGggZD0iTTggMkgydjZtMTQtNmg2djZNMiAxNnY2aDZtOCAwaDZ2LTYiLz4KICAgIDxwYXRoIGQ9Im0xMiA1IDYgMy41djdMMTIgMTlsLTYtMy41di03Wm0tNiAzLjUgNiAzLjUgNi0zLjVNMTIgMTJ2NyIvPgogIDwvZz4KPC9zdmc+Cg==
maintainers:
  - name: core
