# namespace - минимальный рабочий пример.
# Создаёт Namespace и ResourceQuota, без выделенной подсети.

global:
  enable: true

identity:
  instance: ed         # тег инстанса окружения
  cluster: dev         # тег кластера окружения
  project: demo        # тег проекта, до 9 символов

namespace:
  namespaceName: "demo-dev-ns-app"
  projectName: demo
  clusterName: common

resourceQuotas:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: "1"
    memory: "2Gi"

subnet:
  enable: false
