# managed-namespace - minimal working example.
# Creates a Namespace and ResourceQuota (without a dedicated subnet).

global:
  enable: true

namespace:
  namespaceName: "demo-dev-ns-app"
  projectName: demo
  clusterName: common

resourceQuotas:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: "1"
    memory: "2Gi"

subnet:
  enable: false
