{{- if eq (include "namespace.helpers.chartEnabled" .) "true" }}
{{- $identity := .Values.identity | default dict }}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cpaas.io/display-name: {{ .Values.namespace.displayName | default "" | quote }}
    cpaas.io/creator: {{ .Values.namespace.creator | default "lk" }}
    cpaas.io/project-inner-namespace: {{ $identity.project }}
    {{- if .Values.serviceMesh.enabled }}
    networking.k8s.io/enable-netpol: "true"
    {{- end }}
    {{- range $k, $v := (.Values.generic | default dict).annotations }}
    {{ $k }}: {{ tpl (toString $v) $ | quote }}
    {{- end }}
  labels:
    cpaas.io/cluster: {{ $identity.cluster }}
    cpaas.io/project: {{ $identity.project }}
    namespace-role: {{ .Values.namespace.role | default "other" }}
    kubernetes.io/metadata.name: {{ include "namespace.helpers.namespaceName" . }}
    {{- if .Values.serviceMesh.enabled }}
    istio-discovery: enabled
    istio.io/dataplane-mode: ambient
    {{- end }}
    {{- include "namespace.helpers.labels" . | nindent 4 }}
  name: {{ include "namespace.helpers.namespaceName" . }}
#spec: []
{{- end -}}
