apiVersion: v2
name: waypoint
description: Пропускает через себя обмен внутри вашего пространства, чтобы работали правила доступа между сервисами.
type: application
version: 2.0.1
appVersion: "1.0.0"
