apiVersion: v2
name: waypoint
description: Пропускает через себя обмен внутри вашего пространства, чтобы работали правила доступа между сервисами.
type: application
version: 2.3.0
appVersion: "1.0.0"
icon: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgdmlld0JveD0iMCAwIDY0IDY0IiBmaWxsPSJub25lIj4KICA8dGl0bGU+V2F5cG9pbnQ8L3RpdGxlPgogIDxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgcng9IjE2IiBmaWxsPSIjRjFFQUZBIi8+CiAgPGcgdHJhbnNmb3JtPSJzY2FsZSgyLjY2NjY2NjY2NykiIHN0cm9rZT0iIzY4NDBBNSIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+CiAgICA8cGF0aCBkPSJNNyA4VjUuNUExLjUgMS41IDAgMCAxIDguNSA0aDdBMS41IDEuNSAwIDAgMSAxNyA1LjVWOE03IDE2djIuNUExLjUgMS41IDAgMCAwIDguNSAyMGg3YTEuNSAxLjUgMCAwIDAgMS41LTEuNVYxNiIvPgogICAgPHBhdGggZD0iTTIgMTJoN00xNSAxMmg3bS0zLjUtMy41TDIyIDEybC0zLjUgMy41Ii8+CiAgICA8Y2lyY2xlIGN4PSIxMiIgY3k9IjEyIiByPSIzIi8+CiAgPC9nPgo8L3N2Zz4K
maintainers:
  - name: core
