apiVersion: v2
name: waypoint
description: Пропускает через себя обмен внутри вашего пространства, чтобы работали правила доступа между сервисами.
type: application
version: 2.3.0
appVersion: "1.0.0"
icon: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIj4KICA8dGl0bGU+V2F5cG9pbnQ8L3RpdGxlPgogIDxnIHN0cm9rZT0iIzk1NzBDOSIgc3Ryb2tlLXdpZHRoPSIxLjgiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+CiAgICA8cGF0aCBkPSJNNyA2VjMuNUExLjUgMS41IDAgMCAxIDguNSAyaDdBMS41IDEuNSAwIDAgMSAxNyAzLjVWNk03IDE4djIuNUExLjUgMS41IDAgMCAwIDguNSAyMmg3YTEuNSAxLjUgMCAwIDAgMS41LTEuNVYxOCIvPgogICAgPHBhdGggZD0iTTEuNSAxMkg2bTEyIDBoNC41bS0zLTMgMyAzLTMgMyIvPgogICAgPGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMyIvPgogIDwvZz4KPC9zdmc+Cg==
maintainers:
  - name: core
