# Минимальный пример: один waypoint-прокси на namespace.
#
# Имя ресурса по конвенции: {instance}-{cluster}-{kindShort}-{project}-{name}
# С тегами ниже получится:
# - Gateway ed-dev-wp-nbox-mesh

identity:
  instance: ed         # тег инстанса окружения
  cluster: dev         # тег кластера окружения
  project: nbox        # тег проекта, до 9 символов

generic:
  labels: {}
  annotations: {}

waypoints:
  - name: mesh
    enabled: true
    for: service
