apiVersion: v2
name: ingress-gateway
description: Принимает внешний трафик и направляет его в ваш сервис. Настраиваются маршруты, ограничение доступа и вход по единой учётной записи.
type: application
version: 9.0.0
appVersion: "3.2.4"
icon: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIj4KICA8dGl0bGU+SW5ncmVzcyBHYXRld2F5PC90aXRsZT4KICA8ZyBzdHJva2U9IiM1MjdGQzciIHN0cm9rZS13aWR0aD0iMS44IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiPgogICAgPHBhdGggZD0iTTkuNSA2LjV2LTNBMS41IDEuNSAwIDAgMSAxMSAyaDEwYTEuNSAxLjUgMCAwIDEgMS41IDEuNXYxN0ExLjUgMS41IDAgMCAxIDIxIDIySDExYTEuNSAxLjUgMCAwIDEtMS41LTEuNXYtMyIvPgogICAgPHBhdGggZD0iTTEuNSAxMmgxNW0tMy0zIDMgMy0zIDMiLz4KICA8L2c+Cjwvc3ZnPgo=
maintainers:
  - name: core
