apiVersion: v2
name: ingress-gateway
description: Принимает внешний трафик и направляет его в ваш сервис. Настраиваются маршруты, ограничение доступа и вход по единой учётной записи.
type: application
version: 9.0.0
appVersion: "3.2.4"
icon: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgdmlld0JveD0iMCAwIDY0IDY0IiBmaWxsPSJub25lIj4KICA8dGl0bGU+SW5ncmVzcyBHYXRld2F5PC90aXRsZT4KICA8cmVjdCB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHJ4PSIxNiIgZmlsbD0iI0VBRjJGRiIvPgogIDxnIHRyYW5zZm9ybT0ic2NhbGUoMi42NjY2NjY2NjcpIiBzdHJva2U9IiMyNDRCQTMiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiPgogICAgPHBhdGggZD0iTTEwIDhWNS41QTEuNSAxLjUgMCAwIDEgMTEuNSA0aDhBMS41IDEuNSAwIDAgMSAyMSA1LjV2MTNhMS41IDEuNSAwIDAgMS0xLjUgMS41aC04YTEuNSAxLjUgMCAwIDEtMS41LTEuNVYxNiIvPgogICAgPHBhdGggZD0iTTMgMTJoMTIuNW0tMy41LTMuNSAzLjUgMy41LTMuNSAzLjUiLz4KCiAgPC9nPgo8L3N2Zz4K
maintainers:
  - name: core
