apiVersion: v2
name: egress-gateway
description: Выпускает трафик ваших сервисов наружу через одну контролируемую точку. Нужен, когда во внешние системы можно ходить только с известного адреса.
type: application
version: 3.0.3
appVersion: "1.0.0"