# policies - default values (minimum for render to pass).
# By default no policies are created (all lists are empty).
# Full parameter reference - values.full.yaml; working example - values.minimal.yaml.

naming:
  instanceTag: ru1     # required, lower-case DNS format
  clusterTag: k8s1     # required, lower-case DNS format
  projectTag: nbox     # required, 2..6 characters

defaults:
  trustDomain: cluster.local
  namespaceLabelKey: kubernetes.io/metadata.name
  protocol: TCP

policies: []
netpol: []
authzpol: []
